services:
  # Build app from Dockerfile in same folder
  app:
    build: .

  # Build the db as name world from the Dockerfile in the db folder
  world:
    build: db/.
    # keep port forwarding so we can test app locally without docker
    command: --default-authentication-plugin=mysql_native_password
    restart: always